# Generated by Django 4.1.4 on 2023-08-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=100)),
                ("payment_id", models.CharField(max_length=100)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
    ]
